# Generated by Django 5.1.1 on 2024-10-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakshyam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chais/'),
        ),
        migrations.AddField(
            model_name='chaivarity',
            name='ttype',
            field=models.CharField(choices=[('ML', 'Masala'), ('Hr', 'Herbal'), ('Mi', 'Milk'), ('Gr', 'Green')], default=('ML', 'Masala'), max_length=2),
        ),
    ]
