# Generated by Django 5.1.1 on 2024-11-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakshyam', '0002_chaivarity_image_chaivarity_ttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='ttype',
            field=models.CharField(choices=[('ML', 'Masala'), ('Hr', 'Herbal'), ('Mi', 'Milk'), ('Gr', 'Green'), ('Co', 'Coffee')], default=('ML', 'Masala'), max_length=2),
        ),
    ]
