# Generated by Django 5.1.1 on 2024-11-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakshyam', '0003_chaivarity_description_alter_chaivarity_ttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='amount',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
