# Generated by Django 5.1.1 on 2024-12-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakshyam', '0005_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='ttype',
            field=models.CharField(choices=[('ML', 'Masala'), ('Hr', 'Herbal'), ('Mi', 'Milk'), ('Gr', 'Green'), ('Co', 'Coffee')], default='ML', max_length=2),
        ),
    ]
