# Generated by Django 5.1.1 on 2025-01-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakshyam', '0008_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ML', 'Masala'), ('Hr', 'Herbal'), ('Mi', 'Milk'), ('Gr', 'Green'), ('Co', 'Coffee'), ('El', 'Elong'), ('Ma', 'Matcha'), ('Pr', 'Peppermint')], default='ML', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sakshyam.category')),
            ],
        ),
    ]
