# Generated by Django 5.1.1 on 2025-01-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakshyam', '0009_category_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('ML', 'Masala'), ('Hr', 'Herbal'), ('Mi', 'Milk'), ('Gr', 'Green'), ('Co', 'Coffee'), ('El', 'Elong'), ('Ma', 'Matcha'), ('Pr', 'Peppermint')], default='ML', max_length=2, verbose_name='Chai Type'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sakshyam.category', verbose_name='Chai Type'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=1000, verbose_name='Your Feedback'),
        ),
    ]
