# Generated by Django 5.1.1 on 2025-01-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sakshyam', '0010_alter_category_category_alter_feedback_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chaivarity',
            name='ttype',
            field=models.CharField(choices=[('ML', 'Masala'), ('Hr', 'Herbal'), ('Mi', 'Milk'), ('Gr', 'Green'), ('Co', 'Coffee'), ('El', 'Elong'), ('Ma', 'Matcha'), ('Pr', 'Peppermint')], default='ML', max_length=2),
        ),
    ]
